version: '3.1'

services:
  database:
    image: mariadb:10.6.3
    restart: unless-stopped
    env_file:
      - db-config.env
    ports:
      - 3306:3306
    volumes:
      - dbvol:/var/lib/mysql

volumes:
  dbvol: