version: '3.1'

services:
  database:
    image: mariadb:10.6.3
    restart: unless-stopped
    env_file:
      - config.env
      - docker-config.env
    volumes:
      - dbvol:/var/lib/mysql
  application:
    build:
      dockerfile: deployment/Dockerfile
      context: ../
    env_file:
      - config.env
      - docker-config.env
    ports:
      - 8080:8080

volumes:
  dbvol: