apiVersion: v1
kind: Secret
metadata:
    name: advent-secret
type: Opaque
data:
    admin-token: eWVldHllZXQK
    mysql-username: dXNlcgo=
    mysql-root-password: dWx0cmFjb29scGFzc3dvcmR0aGlzaXNkZXZsb2wK
    mysql-password: dWx0cmFjb29scGFzc3dvcmR0aGlzaXNkZXZsb2wK
    jdbc-datasource: amRiYzptYXJpYWRiOi8vbXlzcWw6MzMwNi9hZHZlbnQK
    admin-token: YWdhaW5fcGxhZXNlX2NoYW5nZV90aGlzX3Rva2VuCg==
    jwt-secret: c29tZV9qd3Rfc2VjcmV0X3RoYXRfc2hvdWxkX2Fsc29fY2hhbmdlX2luX3Byb2RfdWp3dXNqa3NoZW5zaXNhX2pzOHduZGdzYWtxbgo=
